/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 cursuch.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cursuch.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Root} />
          <primitive object={nodes.IKLegPoleL} />
          <primitive object={nodes.IKTargetL} />
          <primitive object={nodes.IKLegPoleR} />
          <primitive object={nodes.IKTargetR} />
          <skinnedMesh name="Assistant" geometry={nodes.Assistant.geometry} material={materials.Material} skeleton={nodes.Assistant.skeleton} />
        </group>
        <mesh name="Hat" geometry={nodes.Hat.geometry} material={materials.Material} position={[0, 0.003, 0.069]} rotation={[-0.099, 0.034, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cursuch.glb')
